- name: Create Prowlarr Quadlet File
  become: true
  become_user: '{{ prowlarr_user }}'
  notify: Restart prowlarr
  containers.podman.podman_container:
    name: '{{ prowlarr_container }}'
    image: '{{ prowlarr_image }}'
    state: quadlet
    quadlet_filename: '{{ prowlarr_container }}'
    ports:
      - '{{ prowlarr_http_port | default(9696) }}:9696'
    volumes:
      - '{{ prowlarr_config }}:/config:z'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
