---
- name: Ensure Redis is running
  become: true
  become_user: '{{ redis_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ redis_container }}'
    scope: user
