---
- name: Restart Home Assistant
  become: true
  become_user: '{{ home_assistant_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ home_assistant_container }}'
    scope: user
