---
- name: Ensure Actualbudget is running
  become: true
  become_user: '{{ actualbudget_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ actualbudget_container }}'
    scope: user
