---
- name: Ensure there's a volume to store Actualbudget data
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ actualbudget_data }}'
    podman_user: '{{ actualbudget_user }}'
