---
- name: Restart Immich
  become: true
  become_user: '{{ immich_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ immich_container }}'
    scope: user

- name: Restart Immich Machine Learning
  become: true
  become_user: '{{ immich_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ immich_machine_learning_container }}'
    scope: user

- name: Restart Immich Redis
  become: true
  become_user: '{{ immich_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ immich_redis_container }}'
    scope: user
