---
- name: Restart Prometheus
  become: true
  become_user: "{{ prometheus_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ prometheus_container }}"
    scope: user
