---
- name: Create Trilium Next Quadlet file
  become: true
  become_user: '{{ trilium_user }}'
  notify: Restart Trilium
  containers.podman.podman_container:
    name: '{{ trilium_container }}'
    image: '{{ trilium_image }}'
    state: quadlet
    quadlet_filename: '{{ trilium_container }}'
    ports:
      - '{{ trilium_http_port | default("8080") }}:8080'
    volumes:
      - '{{ trilium_data }}:/home/node/trilium-data:z'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      TRILIUM_DATA_DIR: /home/node/trilium-data
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
