---
- name: Set postgres_volumes fact
  ansible.builtin.set_fact:
    postgres_volumes:
      - '{{ (postgres_data_dir is defined | ternary(postgres_data_dir, postgres_data_vol)) }}:/var/lib/postgresql/data'

- name: Append postgres_init_script volume if defined
  ansible.builtin.set_fact:
    postgres_volumes: "{{ postgres_volumes + [postgres_init_script + ':/docker-entrypoint-initdb.d/initdb.sql:z'] }}"
  when: postgres_init_script is defined

- name: Create Postgres Quadlet file
  become: true
  become_user: '{{ postgres_podman_user }}'
  notify: Restart Postgres
  containers.podman.podman_container:
    name: '{{ postgres_container }}'
    image: '{{ postgres_image | "docker.io/postgres:latest" }}'
    userns: "{{ 'auto' if postgres_data_dir is defined or postgres_init_script is defined else '' }}"
    network: '{{ postgres_network }}'
    state: quadlet
    quadlet_filename: '{{ postgres_container }}'
    ports:
      - '5432:5432'
    volumes: '{{ postgres_volumes }}'
    command: '{{ postgres_command | default(omit) }}'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      POSTGRES_DB: '{{ postgres_db }}'
      POSTGRES_USER: '{{ postgres_user }}'
      POSTGRES_PASSWORD: '{{ postgres_pass }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
