---
- name: Ensure Freshrss is running
  become: true
  become_user: "{{ freshrss_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ freshrss_container }}"
    scope: user
