---
- name: Ensure there's a volume to store Freshrss data
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ freshrss_data }}"
    podman_user: "{{ freshrss_user }}"

- name: Ensure there's a volume to store Freshrss extensions
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ freshrss_extensions }}"
    podman_user: "{{ freshrss_user }}"
