---
- name: Ensure Grafana is running
  become: true
  become_user: '{{ grafana_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ grafana_container }}'
    scope: user
