---
- name: Copy Soularr configuration file
  become: true
  notify: Restart Soularr
  ansible.builtin.template:
    src: templates/config.ini.j2
    dest: '{{ soularr_config_dir }}/config.ini'
    owner: '{{ soularr_user }}'
    group: '{{ soularr_user }}'
    mode: '0755'
