- name: Ensure there's a directory to download files
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ soularr_downloads_dir }}'
    podman_user: '{{ soularr_user }}'

- name: Ensure there's a directory to store the configuration file
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ soularr_config_dir }}'
    podman_user: '{{ soularr_user }}'
