---
- name: Create Soularr Quadlet file
  become: true
  become_user: '{{ soularr_user }}'
  notify: Restart Soularr
  containers.podman.podman_container:
    name: '{{ soularr_container }}'
    image: '{{ soularr_image }}'
    state: quadlet
    quadlet_filename: '{{ soularr_container }}'
    ports:
    volumes:
      - '{{ soularr_downloads_dir }}:/downloads'
      - '{{ soularr_config_dir }}/config.ini:/data/config.ini'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      SCRIPT_INTERVAL: '{{ soularr_run_interval | default(300) }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
