---
- name: Ensure Soularr is running
  become: true
  become_user: '{{ soularr_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ soularr_container }}'
    scope: user
