- name: Ensure there's a directory to download files
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ slskd_downloads_dir }}'
    podman_user: '{{ slskd_user }}'

- name: Ensure there's a directory to share files
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ slskd_shared_dir }}'
    podman_user: '{{ slskd_user }}'
