---
- name: Ensure Slskd is running
  become: true
  become_user: '{{ slskd_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ slskd_container }}'
    scope: user
