incus_token = "eyJjbGllbnRfbmFtZSI6ImxhcHRvcCIsImZpbmdlcnByaW50IjoiYzgwMWYxYjA5MzU4ZDAxNGNkNDlhZWMxMzBlM2MzNTgxMGZiZGNiOGZjNjFkNTAyOWNlZmYwOTEwNzVmYTUwMCIsImFkZHJlc3NlcyI6WyIxMC4wLjAuMTE6ODQ0MyIsIjEwLjE0Ny43OS4xOjg0NDMiLCJbZmQ0Mjo1YjllOjYwMzU6NGQ1Nzo6MV06ODQ0MyJdLCJzZWNyZXQiOiIxYjMwY2Q0M2RhNjlkZGU0OGE1ZmY0NzJhZDYwNzY5ODY0ZDhjMDFjYTY0YTgyM2M1MGE4YmFlZDZmYzZhODNkIiwiZXhwaXJlc19hdCI6IjAwMDEtMDEtMDFUMDA6MDA6MDBaIn0="

main_storage_size = "4GiB"
main_storage_source = "main"

high_io_storage_size = "4GiB"
high_io_storage_source = "high-io"
