FROM caddy:builder AS builder

{% set extensions = caddy_extensions | join(' --with ') %}

RUN xcaddy build --with {{ extensions }}

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
