---
- name: Ensure there's a directory to store pihole wildcard domains config
  become: true
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: "{{ pihole_wildcards_dir }}"
    podman_user: "{{ pihole_user }}"
