---
- name: Allow usage of privileged ports by rootless processes
  ansible.builtin.import_role:
    name: podman
    tasks_from: rootless_ports
- name: Directory configuration
  ansible.builtin.import_tasks: directories.yml
- name: Wildcard domains configuration
  ansible.builtin.import_tasks: wildcards.yml
- name: Quadlet(s) configuration
  ansible.builtin.import_tasks: quadlet.yml
- name: Services configuration
  ansible.builtin.import_tasks: service.yml
