---
- name: Create Pihole DNS Quadlet file
  become: true
  become_user: "{{ pihole_user }}"
  notify: Restart pihole
  containers.podman.podman_container:
    name: "{{ pihole_container }}"
    image: docker.io/pihole/pihole:latest
    state: quadlet
    quadlet_filename: "{{ pihole_container }}"
    ports:
      - "{{ pihole_http_port | default(8080) }}:80/tcp"
      - "{{ pihole_dns_port | default(53) }}:53/tcp"
      - "{{ pihole_dns_port | default(53) }}:53/udp"
    volumes:
      - "{{ pihole_data_vol }}:/etc/pihole:z"
      - "{{ pihole_wildcards_dir }}/99-wildcard-domains.conf:/etc/dnsmasq.d/99-wildcard-domains.conf:z"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ tz }}"
      FTLCONF_webserver_api_password: "{{ pihole_http_pass }}"
      FTLCONF_dns_listeningMode: "{{ pihole_dns_listen_mode }}"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
