---
- name: Ensure Pihole DNS server is running
  become: true
  become_user: '{{ pihole_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ pihole_container }}'
    scope: user
