---
- name: Ensure systemd-resolved is stopped and disabled
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Delete resolv.conf in case it is symlinked
  become: true
  ansible.builtin.file:
    path: "/etc/resolv.conf"
    state: absent

- name: Ensure resolv.conf is present
  become: true
  ansible.builtin.copy:
    src: "files/resolv.conf"
    dest: "/etc/resolv.conf"
    owner: "root"
    group: "root"
    mode: "0644"
