- name: Configure bastion virtual machine
  hosts: bastion
  vars:
    bastion_guacamole_postgres_db: guacamole_postgres
    bastion_guacamole_postgres_user: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62386163343761343964356335636266333966313163666465613265363939616264633938613465
      6264346664373834346439333834393039663863306536320a336462623838636339653461306162
      30383633363132353733633065313937306464396462656637376266626530623039653338613931
      3533663733363566660a343466303464663865383464356264393635653134646264653430323338
      3963
    bastion_guacamole_postgres_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38643365383938646666313537646136306630396464616234636535353336303666646433616362
      3263316666353133306235323563663734313336313132610a633538343239303132633866613836
      31343432336464643137346235376663656262386434303737393061366631313961616166656236
      3732303938323461380a333363393230383766363263363630356662643131376330383638303134
      6337
  tasks:
    - name: Login to homelab registry
      ansible.builtin.import_role:
        name: podman
        tasks_from: login
      vars:
        podman_login_registry: '{{ registry_host }}.{{ internet_host }}'
        podman_login_user: '{{ homelab_registry_user }}'
        podman_login_pass: '{{ homelab_registry_pass }}'
        podman_user: '{{ container_user }}'

    - name: Ensure there's a directory to store guacamole-web init script
      become: true
      ansible.builtin.file:
        path: '/var/guacamole_web'
        owner: '{{ container_user }}'
        group: '{{ container_user }}'
        state: directory
        mode: '0777'

    - name: Ensure initdb script is present on the host
      become: true
      ansible.builtin.copy:
        src: 'files/guacamole/initdb.sql'
        dest: '/var/guacamole_web/initdb.sql'
        mode: '0777'
        owner: '{{ container_user }}'
        group: '{{ container_user }}'

    - name: Deploy Postgres for Guacamole
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: guacamole_postgres
          image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/library/postgres:latest'
          registry_user: '{{ homelab_registry_user }}'
          registry_pass: '{{ homelab_registry_pass }}'
          user: '{{ container_user }}'
          userns: 'auto'
          networks:
            - name: guacamole
          ports:
            - '5432:5432'
          volumes:
            - name: 'guacamole_postgres'
              dest: '/var/lib/postgresql/data:z'
          file_mounts:
            - src: '/var/guacamole_web/initdb.sql'
              dest: '/docker-entrypoint-initdb.d/initdb.sql:z'
          env:
            POSTGRES_DB: '{{ bastion_guacamole_postgres_db }}'
            POSTGRES_USER: '{{ bastion_guacamole_postgres_user }}'
            POSTGRES_PASSWORD: '{{ bastion_guacamole_postgres_pass }}'

    - name: Deploy Guacamole guacd
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: guacamole_guacd
          image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/guacamole/guacd:latest'
          registry_user: '{{ homelab_registry_user }}'
          registry_pass: '{{ homelab_registry_pass }}'
          user: '{{ container_user }}'
          networks:
            - name: guacamole
          ports:
            - '4822:4822'

    - name: Deploy Guacamole web
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: guacamole_web
          image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/guacamole/guacamole:latest'
          registry_user: '{{ homelab_registry_user }}'
          registry_pass: '{{ homelab_registry_pass }}'
          user: '{{ container_user }}'
          networks:
            - name: guacamole
          ports:
            - '8081:8080'
          env:
            GUACD_HOSTNAME: 'guacamole_guacd'
            GUACD_PORT: '4822'
            POSTGRESQL_HOSTNAME: '{{ bastion_guacamole_postgres_db }}'
            POSTGRESQL_DATABASE: '{{ bastion_guacamole_postgres_db }}'
            POSTGRESQL_USER: '{{ bastion_guacamole_postgres_user }}'
            POSTGRESQL_PASSWORD: '{{ bastion_guacamole_postgres_pass }}'
            EXTENSION_PRIORITY: 'openid,postgresql'
            OPENID_AUTHORIZATION_ENDPOINT: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/protocol/openid-connect/auth'
            OPENID_JWKS_ENDPOINT: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/protocol/openid-connect/certs'
            OPENID_ISSUER: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}'
            OPENID_CLIENT_ID: '{{ remote_client }}'
            OPENID_REDIRECT_URI: 'https://{{ remote_host }}.{{ internet_host }}'
            WEBAPP_CONTEXT: 'ROOT'
            LOG_LEVEL: 'debug'
