- name: Configure bastion virtual machine
  hosts: bastion
  vars:
    bastion_user: bastion
    bastion_guacamole_network: guacamole
    bastion_guacamole_postgres_db: guacamole_postgres
    bastion_guacamole_postgres_user: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62386163343761343964356335636266333966313163666465613265363939616264633938613465
      6264346664373834346439333834393039663863306536320a336462623838636339653461306162
      30383633363132353733633065313937306464396462656637376266626530623039653338613931
      3533663733363566660a343466303464663865383464356264393635653134646264653430323338
      3963
    bastion_guacamole_postgres_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38643365383938646666313537646136306630396464616234636535353336303666646433616362
      3263316666353133306235323563663734313336313132610a633538343239303132633866613836
      31343432336464643137346235376663656262386434303737393061366631313961616166656236
      3732303938323461380a333363393230383766363263363630356662643131376330383638303134
      6337
  tasks:

    - name: Login to homelab registry
      ansible.builtin.import_role:
        name: podman
        tasks_from: login
      vars:
        podman_login_registry: '{{ registry_host }}.{{ internet_host }}'
        podman_login_user: '{{ homelab_registry_user }}'
        podman_login_pass: '{{ homelab_registry_pass }}'
        podman_user: '{{ bastion_user }}'

    - name: Ensure Guacamole database init script is present
      ansible.builtin.import_role:
        name: guacamole_web
        tasks_from: initdb.yml
      vars:
        guacamole_web_user: '{{ bastion_user }}'
        guacamole_web_initdb_path: '/var/guacamole_web'

    # - name: Deploy Postgres for Guacamole
    #   ansible.builtin.import_role:
    #     name: postgres
    #   vars:
    #     postgres_podman_user: '{{ bastion_user }}'
    #     postgres_container: '{{ bastion_guacamole_postgres_db }}'
    #     postgres_data_vol: 'guacamole_postgres'
    #     postgres_db: '{{ bastion_guacamole_postgres_db }}'
    #     postgres_user: '{{ bastion_guacamole_postgres_user }}'
    #     postgres_pass: '{{ bastion_guacamole_postgres_pass }}'
    #     postgres_network: '{{ bastion_guacamole_network }}'
    #     postgres_init_script: '{{ bastion_guacamole_postgres_init_dir }}/initdb.sql'

    - name: Deploy Postgres for Guacamole
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: guacamole_postgres
          image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/library/postgres:latest'
          user: '{{ container_user }}'
          userns: 'auto'
          networks:
            - name: guacamole
          ports:
            - '5432:5432'
          volumes:
            - name: 'guacamole_postgres'
              dest: '/var/lib/postgresql/data:z'
          bind_mounts:
            - src: '/var/guacamole_web/initdb.sql'
              dest: '/docker-entrypoint-initdb.d/initdb.sql:z'
              type: 'file'
          env:
            POSTGRES_DB: '{{ bastion_guacamole_postgres_db }}'
            POSTGRES_USER: '{{ bastion_guacamole_postgres_user }}'
            POSTGRES_PASSWORD: '{{ bastion_guacamole_postgres_pass }}'

    # - name: Deploy Guacamole guacd
    #   ansible.builtin.import_role:
    #     name: guacamole_guacd
    #   vars:
    #     guacamole_guacd_user: '{{ bastion_user }}'
    #     guacamole_guacd_container: guacamole_guacd
    #     guacamole_guacd_network: '{{ bastion_guacamole_network }}'
    #     guacamole_guacd_image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/guacamole/guacd:latest'

    - name: Deploy Guacamole guacd
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: guacamole_guacd
          image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/guacamole/guacd:latest'
          user: '{{ container_user }}'
          networks:
            - name: guacamole
          ports:
            - '4822:4822'

    - name: Deploy Guacamole web
      ansible.builtin.import_role:
        name: guacamole_web
      vars:
        guacamole_web_user: '{{ bastion_user }}'
        guacamole_web_port: '8081'
        guacamole_web_container: guacamole_web
        guacamole_web_image: '{{ registry_host }}.{{ internet_host }}/dockerhub-proxy/guacamole/guacamole:latest'
        guacamole_web_network: '{{ bastion_guacamole_network }}'
        guacamole_web_guacd_hostname: guacamole_guacd
        guacamole_web_extension_priority: 'openid,postgresql'
        guacamole_web_openid_authorization_endpoint: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/protocol/openid-connect/auth'
        guacamole_web_openid_jwks_endpoint: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/protocol/openid-connect/certs'
        guacamole_web_openid_issuer: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}'
        guacamole_web_openid_client_id: '{{ remote_client }}'
        guacamole_web_openid_redirect_uri: 'https://{{ remote_host }}.{{ internet_host }}'
        guacamole_web_pg_host: '{{ bastion_guacamole_postgres_db }}'
        guacamole_web_pg_db: '{{ bastion_guacamole_postgres_db }}'
        guacamole_web_pg_user: '{{ bastion_guacamole_postgres_user }}'
        guacamole_web_pg_pass: '{{ bastion_guacamole_postgres_pass }}'
