- name: Configure Container host virtual machine
  hosts: container_hosts
  vars:
    container_host_user: container-host

  tasks:
    - name: Deploy Docker CE
      ansible.builtin.import_role:
        name: docker_host
