- name: Common configuration for all DNS servers
  hosts: vpn_dns, home_dns
  tasks:
    - name: Allow usage of privileged ports by rootless processes
      ansible.builtin.import_role:
        name: podman
        tasks_from: rootless_ports

    - name: Ensure systemd-resolved is stopped and disabled
      become: true
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Delete resolv.conf in case it is symlinked
      become: true
      ansible.builtin.file:
        path: "/etc/resolv.conf"
        state: absent

    - name: Ensure resolv.conf is present
      become: true
      ansible.builtin.copy:
        src: "files/pihole/resolv.conf"
        dest: "/etc/resolv.conf"
        owner: "root"
        group: "root"
        mode: "0644"


- name: Configure DNS Servers
  hosts: vpn_dns, home_dns
  vars:
    dns_sync_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663931303761383032353263643234333766623731323062383935626230666433646633303837
          6465323665326566656235373031353566663939306163660a656464306663663835303964323564
          34666662366430666339666561383439633638386635653262386266623061323739383530313765
          6564323538613133300a613466343737303632373035666361373738623137626239353730346166
          6666
  tasks:
    - name: Template wildcard dns configuration
      become: true
      ansible.builtin.template:
        src: "templates/pihole/wildcard-domains.conf.j2"
        dest: "/var/pihole/99-wildcard-domains.conf"
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: "0755"
      vars:
        pihole_wildcard_records: []

    - name: Deploy pi-hole
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: 'pihole'
          user: '{{ container_user }}'
          image: 'docker.io/pihole/pihole:latest'
          host_network: true
          volumes:
            - name: 'pihole_data'
              dest: '/etc/pihole:z'
          file_mounts:
            - src: '/var/pihole/99-wildcard-domains.conf'
              dest: '/etc/dnsmasq.d/99-wildcard-domains.conf:z'
          env:
            FTLCONF_webserver_api_password: "{{ dns_sync_pass }}"
            FTLCONF_dns_listeningMode: "all"
          cap_add:
            - NET_ADMIN
            - SYS_TIME
            - SYS_NICE

- name: Configure VPN DNS Sync
  hosts: primary_vpn_dns
  vars:
    dns_sync_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66663931303761383032353263643234333766623731323062383935626230666433646633303837
      6465323665326566656235373031353566663939306163660a656464306663663835303964323564
      34666662366430666339666561383439633638386635653262386266623061323739383530313765
      6564323538613133300a613466343737303632373035666361373738623137626239353730346166
      6666
  tasks:
    - name: Deploy nebula-sync
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: 'pihole-nebula-sync'
          user: '{{ container_user }}'
          image: 'ghcr.io/lovelaze/nebula-sync:latest'
          env:
            PRIMARY: "http://host.containers.internal:80|{{ dns_sync_pass }}"
            REPLICAS: "http://10.0.2.5:80|{{ dns_sync_pass }},http://100.64.0.1:80|{{ dns_sync_pass }}"
            CRON: '"0 */6 * * *"'
            FULL_SYNC: "true"
            RUN_GRAVITY: "true"

- name: Configure home DNS Sync
  hosts: primary_home_dns
  tasks:
    - name: Deploy nebula-sync
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: 'pihole-nebula-sync'
          user: '{{ container_user }}'
          image: 'ghcr.io/lovelaze/nebula-sync:latest'
          env:
            PRIMARY: "http://host.containers.internal:80|{{ dns_sync_pass }}"
            REPLICAS: "http://10.0.2.3:80|{{ dns_sync_pass }},http://100.64.0.16:80|{{ dns_sync_pass }}"
            CRON: '"0 */6 * * *"'
            FULL_SYNC: "true"
            RUN_GRAVITY: "true"
