- name: Common configuration for all DNS servers
  hosts: home_dns
  tasks:
    - name: Allow usage of privileged ports by rootless processes
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.podman
        tasks_from: rootless_ports

    - name: Ensure systemd-resolved is stopped and disabled
      become: true
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Ensure resolv.conf is absent even as a symbolic link
      become: true
      ansible.builtin.file:
        path: '/etc/resolv.conf'
        state: absent

    - name: Ensure working resolv.conf file is present
      become: true
      ansible.builtin.copy:
        src: 'files/blocky/resolv.conf'
        dest: '/etc/resolv.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

- name: Configure DNS Servers
  hosts: home_dns
  tasks:
    - name: Ensure there's a directory to store blocky configuration
      ansible.builtin.file:
        path: '/var/blocky'
        state: directory
        owner: '{{ container_user }}'
        group: '{{ container_user }}'
        mode: '0755'

    - name: Ensure Blocky DNS config file is present
      ansible.builtin.template:
        src: 'files/blocky/config.yml.j2'
        dest: '/var/blocky/config.yml'
        owner: '{{ container_user }}'
        group: '{{ container_user }}'
        mode: '0644'

    - name: Deploy Blocky DNS server
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: 'blocky'
          user: '{{ container_user }}'
          image: 'docker.io/pihole/pihole:latest'
          host_network: false
          ports:
            - '5353:53/udp'
          file_mounts:
            - src: '/var/blocky/config.yml'
              dest: '/app/config.yml:ro,z'
          # cap_add:
          #   - NET_ADMIN
          #   - SYS_TIME
          #   - SYS_NICE
