- name: Configure virtual machines and home DNS server
  hosts: home_dns
  vars:
    dns_sync_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663931303761383032353263643234333766623731323062383935626230666433646633303837
          6465323665326566656235373031353566663939306163660a656464306663663835303964323564
          34666662366430666339666561383439633638386635653262386266623061323739383530313765
          6564323538613133300a613466343737303632373035666361373738623137626239353730346166
          6666
  tasks:

    - name: Build dns_records from homelab_services
      ansible.builtin.set_fact:
        dns_records: "{{ dns_records | default([]) + [ { 'domain': item.value.host ~ '.' ~ internet_host, 'address': item.value.private_proxy } ] }}"
      loop: "{{ homelab_services | dict2items }}"
      when: item.value.private_proxy is defined

    - name: Show DNS records to be installed
      ansible.builtin.debug:
        msg: '{{ dns_records }}'

    - name: Deploy Pi-Hole
      ansible.builtin.import_role:
        name: pihole
      vars:
        pihole_user: "{{ container_user }}"
        pihole_container: "pihole"
        pihole_http_port: "8080"
        pihole_dns_port: "53"
        pihole_data_vol: "pihole_data"
        pihole_dns_listen_mode: "all"
        pihole_http_pass: '{{ dns_sync_pass }}'
        pihole_wildcards_dir: "/var/pihole"
        pihole_wildcard_records: []

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: '{{ siem_agent }}'
        wazuh_agent_groups: '{{ groups }}'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: '{{ siem_agent }}'
        wazuh_agent_groups: '{{ groups }}'
