- name: Configure VPN DNS Servers
  hosts: vpn_dns
  vars:
    dns_sync_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663931303761383032353263643234333766623731323062383935626230666433646633303837
          6465323665326566656235373031353566663939306163660a656464306663663835303964323564
          34666662366430666339666561383439633638386635653262386266623061323739383530313765
          6564323538613133300a613466343737303632373035666361373738623137626239353730346166
          6666
  tasks:
    - name: Allow usage of privileged ports by rootless processes
      ansible.builtin.import_role:
        name: podman
        tasks_from: rootless_ports

    - name: Ensure systemd-resolved is stopped and disabled
      become: true
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Delete resolv.conf in case it is symlinked
      become: true
      ansible.builtin.file:
        path: "/etc/resolv.conf"
        state: absent

    - name: Ensure resolv.conf is present
      become: true
      ansible.builtin.copy:
        src: "files/resolv.conf"
        dest: "/etc/resolv.conf"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Template wildcard dns configuration
      become: true
      ansible.builtin.template:
        src: "templates/wildcard-domains.conf.j2"
        dest: "/var/pihole/99-wildcard-domains.conf"
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: "0755"

    # - name: Deploy Pi-Hole
    #   ansible.builtin.import_role:
    #     name: pihole
    #   vars:
    #     pihole_user: "{{ container_user }}"
    #     pihole_container: "pihole"
    #     pihole_data_vol: "pihole_data"
    #     pihole_dns_listen_mode: "all"
    #     pihole_http_pass: '{{ dns_sync_pass }}'
    #     pihole_wildcards_dir: "/var/pihole"
    #     pihole_wildcard_records: []

    - name: Deploy pi-hole
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: 'pihole'
          image: 'docker.io/pihole/pihole:latest'
          host_network: true
          volumes:
            - name: 'pihole_data'
              dest: '/etc/pihole:z'
          file_mounts:
            - src: '/var/pihole/99-wildcard-domains.conf'
              dest: '/etc/dnsmasq.d/99-wildcard-domains.conf:z'
          env:
            FTLCONF_webserver_api_password: "dns_sync_pass"
            FTLCONF_dns_listeningMode: "all"
          cap_add:
            - NET_ADMIN
            - SYS_TIME
            - SYS_NICE

- name: Configure VPN DNS Sync
  hosts: primary_vpn_dns
  vars:
    dns_sync_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66663931303761383032353263643234333766623731323062383935626230666433646633303837
      6465323665326566656235373031353566663939306163660a656464306663663835303964323564
      34666662366430666339666561383439633638386635653262386266623061323739383530313765
      6564323538613133300a613466343737303632373035666361373738623137626239353730346166
      6666
  tasks:
    - name: Deploy nebula-sync
      ansible.builtin.import_role:
        name: pihole_nebula_sync
      vars:
        pihole_nebula_sync_user: "{{ container_user }}"
        pihole_nebula_sync_container: "pihole-nebula-sync"
        pihole_nebula_sync_primary: "http://host.containers.internal:80|{{ dns_sync_pass }}"
        pihole_nebula_sync_replicas:
          - "http://10.0.2.5:80|{{ dns_sync_pass }}"
          - "http://100.64.0.1:80|{{ dns_sync_pass }}"
        pihole_nebula_sync_cron: '"0 */6 * * *"'
        pihole_nebula_sync_full_sync: "true"
        pihole_nebula_sync_run_gravity: "true"
