- name: Configure game server hosting machine
  hosts: game_servers
  tasks:

    - name: Login to homelab registry
      ansible.builtin.import_role:
        name: podman
        tasks_from: login
      vars:
        podman_login_registry: '{{ registry_host }}.{{ internet_host }}'
        podman_login_user: '{{ homelab_registry_user }}'
        podman_login_pass: '{{ homelab_registry_pass }}'
        podman_user: '{{ container_user }}'

    - name: Deploy Terraria server
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: terraria_server
          image: '{{ registry_host }}.{{ internet_host }}/ghcr-proxy/beardedio/terraria:vanilla-latest'
          user: '{{ container_user }}'
          volumes:
            - name: 'terraria-work-data'
              dest: ':/config:z'
          ports:
            - '7777:7777'
          env:
            - world: 'terraria-vcsoft.wld'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: '{{ siem_agent }}'
        wazuh_agent_groups: '{{ groups }}'
