- name: Configure game server hosting machine
  hosts: game_servers
  tasks:

    - name: Login to homelab registry
      ansible.builtin.import_role:
        name: podman
        tasks_from: login
      vars:
        podman_login_registry: '{{ registry_host }}.{{ internet_host }}'
        podman_login_user: '{{ homelab_registry_user }}'
        podman_login_pass: '{{ homelab_registry_pass }}'
        podman_user: '{{ game_server_user }}'

    - name: Deploy Terraria Server for workmates
      ansible.builtin.import_role:
        name: terraria_server
      vars:
        terraria_server_user: '{{ game_server_user }}'
        terraria_server_container: 'terraria-work'
        terraria_server_image: '{{ registry_host }}.{{ internet_host }}/ghcr-proxy/beardedio/terraria:vanilla-latest'
        terraria_server_port: '7777'
        terraria_server_data: 'terraria-work-data'
        terraria_server_worldname: 'terraria-vcsoft'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: '{{ siem_agent }}'
        wazuh_agent_groups: '{{ groups }}'
