- name: Configure hypervisor(s)
  hosts: hypervisors
  tasks:
    - name: Ensure the powertop package is installed
      become: true
      ansible.builtin.package:
        name: powertop
        state: present

    - name: Ensure powertop is running and starts on boot
      become: true
      ansible.builtin.service:
        name: powertop
        state: started
        enabled: true

    - name: Cockpit configuration
      ansible.builtin.import_role:
        name: cockpit

    # - name: OpenRGB configuration
    #   ansible.builtin.import_role:
    #     name: openrgb

    - name: Incus configuration
      ansible.builtin.import_role:
        name: incus_server
