- name: Configure knowledge virtual machine
  hosts: knowledge
  tasks:
    - name: Deploy Trilium Next
      ansible.builtin.import_role:
        name: trilium
      vars:
        trilium_user: '{{ knowledge_user }}'
        trilium_container: 'trilium'
        trilium_http_port: '8080'
        trilium_data: 'trilium_data'

    - name: Deploy oauth2_proxy for Trilium next
      ansible.builtin.import_role:
        name: oauth2_proxy
      vars:
        oauth2_proxy_user: '{{ knowledge_user }}'
        oauth2_proxy_container: 'trillium-oauth2-proxy'
        oauth2_proxy_port: '4180'
        oauth2_proxy_email_domains: '*'
        oauth2_proxy_reverse: 'true'
        oauth2_proxy_cookie_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30376532643966303065303333336564623562646163323736376430303232383534316433306562
          3462323365343434316663383832653263343565636263350a633234323036326438303761623534
          35393134613130633839613764363332663630353334626630393834323462633335326639656162
          6430356634336463330a383363326338616538356439353538313365613263663663653931633266
          37656364656165383463366561363562666362636532313632303262656430616664303832616533
          6135323030613139316135303366613033663133383066623166
        oauth2_proxy_whitelist_domains: "['.{{ internet_host }}']"
        oauth2_proxy_cookie_domains: "['.{{ internet_host }}']"
        oauth2_proxy_provider: '{{ homelab_oidc_provider }}'
        oauth2_proxy_client_id: '{{ notes_client }}'
        oauth2_proxy_client_secret: '{{ notes_secret }}'
        oauth2_proxy_redirect_url: 'https://{{ notes_host }}.{{ internet_host }}/oauth2/callback'
        oauth2_proxy_oidc_url: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}'
        oauth2_proxy_allow_unverified_email: 'true'

    - name: Deploy Freshrss
      ansible.builtin.import_role:
        name: freshrss
      vars:
        freshrss_user: '{{ knowledge_user }}'
        freshrss_container: 'freshrss'
        freshrss_http_port: '8081'
        freshrss_data: 'freshrss_data'
        freshrss_extensions: 'freshrss_extensions'
        freshrss_oidc_enabled: '1'
        freshrss_oidc_provider_metadata_url: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/.well-known/openid-configuration'
        freshrss_oidc_client_id: '{{ rss_client }}'
        freshrss_oidc_client_secret: '{{ rss_secret }}'
        freshrss_oidc_x_forwarded_headers: 'X-Forwarded-Host'

    - name: Deploy Actualbudget
      ansible.builtin.import_role:
        name: actualbudget
      vars:
        actualbudget_user: '{{ knowledge_user }}'
        actualbudget_container: 'actualbudget'
        actualbudget_http_port: '5006'
        actualbudget_data: 'actualbudget_data'
        actualbudget_openid_discovery_url: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/.well-known/openid-configuration'
        actualbudget_openid_client_id: '{{ budget_client }}'
        actualbudget_openid_client_secret: '{{ budget_secret }}'
        actualbudget_openid_server_hostname: 'https://{{ budget_host }}.{{ internet_host }}'
        actualbudget_openid_force: 'true'
