- name: Configure public DNS
  hosts: localhost
  tasks:
    - name: Deploy Cloudflare DNS records
      ansible.builtin.import_role:
        name: cloudflare_dns
  vars:
    cloudflare_dns_zone: '{{ internet_host }}'
    cloudflare_dns_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39366537393136653033386238343137366562646362633939643366323935373937356461343938
      6363336636306131653865373361323761646435366638650a303731623236346338333430666634
      37653266333261353132343836613435323736326331386333386666656330616662306335623036
      3736613364336239300a313233653037636236306238333834303864376334336439316133396436
      37663637366631373164656439393866393664386163616561643631396263386162346566646335
      6165613033623131363139303138643833383766336464613631
    cloudflare_dns_data:
      - record: '{{ password_mgr_host }}'
        comment: 'Password Manager'
        value: '{{ public_ip }}'
      - record: '{{ vpn_host }}'
        comment: 'VPN Service'
        value: '{{ public_ip }}'
      - record: '{{ auth_host }}'
        comment: 'Authentication and SSO'
        value: '{{ public_ip }}'
      - record: '{{ music_host }}'
        comment: 'Music Service'
        value: '{{ public_ip }}'
      - record: '{{ notes_host }}'
        comment: 'Note taking Service'
        value: '{{ public_ip }}'
      - record: '{{ code_personal_host }}'
        comment: 'Personal VSCode Server'
        value: '{{ public_ip }}'
      - record: '{{ remote_host }}'
        comment: 'Bastion WebUI'
        value: '{{ public_ip }}'
      - record: '{{ photos_host }}'
        comment: 'Photos Service'
        value: '{{ public_ip }}'
      - record: '{{ metrics_host }}'
        comment: 'Metrics Service'
        value: '{{ public_ip }}'
      - record: '{{ registry_host }}'
        comment: 'Registry Service'
        value: '{{ public_ip }}'
      - record: '{{ home_assistant_host }}'
        comment: 'Home Assistant'
        value: '{{ public_ip }}'
      - record: '{{ remote_ssh_host }}'
        comment: 'Termix'
        value: '{{ public_ip }}'
      - record: '{{ cicd_host }}'
        comment: 'Woodpecker'
        value: '{{ public_ip }}'
