- name: Configure Termix
  hosts: hetzner-remote
  tags:
    - termix-deploy
  tasks:
    - name: Login to homelab registry - Public Internet
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.podman
        tasks_from: login
      vars:
        podman_login_registry: '{{ registry_host }}.{{ internet_host }}:443'
        podman_login_user: '{{ homelab_registry_user }}'
        podman_login_pass: '{{ homelab_registry_pass }}'
        podman_user: '{{ container_user }}'

    - name: Deploy Termix
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: termix
          image: '{{ registry_host }}.{{ internet_host }}:443/ghcr/lukegus/termix:latest'
          user: '{{ container_user }}'
          ports: '8080:8080'
          volumes:
            - name: 'termix_data'
              dest: '/app/data:z'
          env:
            PORT: '8080'
