- name: Configure servarr
  hosts: servarr
  vars:
    servarr_user: servarr
    servarr_downloads: /downloads
    servarr_music: /music
    servarr_cache: /var/servarr-cache

  tasks:

    - name: Login to homelab registry
      ansible.builtin.import_role:
        name: podman
        tasks_from: login
      vars:
        podman_login_registry: '{{ registry_host }}.{{ internet_host }}'
        podman_login_user: '{{ homelab_registry_user }}'
        podman_login_pass: '{{ homelab_registry_pass }}'
        podman_user: '{{ servarr_user }}'

    - name: Deploy tdarr
      ansible.builtin.import_role:
        name: tdarr
      vars:
        tdarr_user: '{{ servarr_user }}'
        tdarr_container: tdarr
        tdarr_http_port: 8265
        tdarr_server_port: 8266
        tdarr_data: tdarr_data
        tdarr_cache: '{{ servarr_cache }}'
        tdarr_library: '{{ servarr_music }}'
        tdarr_server: tdarr_server
        tdarr_image: '{{ registry_host }}.{{ internet_host }}/ghcr-proxy/haveagitgat/tdarr:latest'

    - name: Deploy Flaresolverr
      ansible.builtin.import_role:
        name: flaresolverr
      vars:
        flaresolverr_user: '{{ servarr_user }}'
        flaresolverr_container: flaresolverr
        flaresolverr_image: '{{ registry_host }}.{{ internet_host }}/ghcr-proxy/flaresolverr/flaresolverr:latest'
        flaresolverr_http_port: 8191

    - name: Deploy Prowlarr
      ansible.builtin.import_role:
        name: prowlarr
      vars:
        prowlarr_user: '{{ servarr_user }}'
        prowlarr_container: prowlarr
        prowlarr_image: '{{ registry_host }}.{{ internet_host }}/lscr-proxy/linuxserver/prowlarr:latest'
        prowlarr_config: prowlarr_data
        prowlarr_http_port: 9696

    # - name: Deploy Lidarr
    #   ansible.builtin.import_role:
    #     name: lidarr
    #   vars:
    #     lidarr_user: '{{ servarr_user }}'
    #     lidarr_container: lidarr
    #     lidarr_config: lidarr_data
    #     lidarr_collection: '{{ servarr_music }}'
    #     lidarr_downloads: '{{ servarr_downloads }}'
    #     lidarr_http_port: 8686
    #     lidarr_image: '{{ registry_host }}.{{ internet_host }}/lscr-proxy/linuxserver/lidarr:latest'

    - name: Deploy Lidarr
      ansible.builtin.import_role:
        name: dpkg_i_foo_deb.homelab.quadlet_service
      vars:
        quadlet_service_definition:
          name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          user: '{{ servarr_user }}'
          ports:
            - host_port: 8686
              container_port: 8686
          volumes:
            - name: 'lidarr_data'
              dest: '/config:z'
          bind_mounts:
            - src: '/music'
              dest: '/music:z'
            - src: '/downloads'
              dest: '/downloads:z'


    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: 'servarr'
        wazuh_agent_groups: 'high_risk'
