- name: Configure servarr
  hosts: servarr
  vars:
    servarr_user: servarr
    servarr_downloads: /downloads
    servarr_music: /music
    servarr_cache: /var/servarr-cache

  tasks:

    - name: Deploy tdarr
      ansible.builtin.import_role:
        name: tdarr
      vars:
        tdarr_user: '{{ servarr_user }}'
        tdarr_container: tdarr
        tdarr_http_port: 8265
        tdarr_server_port: 8266
        tdarr_data: tdarr_data
        tdarr_cache: '{{ servarr_cache }}'
        tdarr_library: '{{ servarr_music }}'
        tdarr_server: tdarr_server

    - name: Deploy Flaresolverr
      ansible.builtin.import_role:
        name: flaresolverr
      vars:
        flaresolverr_user: '{{ servarr_user }}'
        flaresolverr_container: flaresolverr
        flaresolverr_http_port: 8191

    - name: Deploy Prowlarr
      ansible.builtin.import_role:
        name: prowlarr
      vars:
        prowlarr_user: '{{ servarr_user }}'
        prowlarr_container: prowlarr
        prowlarr_config: prowlarr_data
        prowlarr_http_port: 9696

    - name: Deploy Lidarr
      ansible.builtin.import_role:
        name: lidarr
      vars:
        lidarr_user: '{{ servarr_user }}'
        lidarr_container: lidarr
        lidarr_config: lidarr_data
        lidarr_collection: '{{ servarr_music }}'
        lidarr_downloads: '{{ servarr_downloads }}'
        lidarr_http_port: 8686

    - name: Deploy LidaTube
      ansible.builtin.import_role:
        name: lidatube
      vars:
        lidatube_user: '{{ servarr_user }}'
        lidatube_container: lidatube
        lidatube_config: lidatube_data
        lidatube_downloads: '{{ servarr_music }}'
        lidatube_http_port: 5000
        lidatube_lidarr_addr: 'http://host.containers.internal:8686'
        lidatube_lidarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66376264613665383264326537626434386330303835333532613763393333393838306632363863
          3264653666396630396437633966346664346161306432330a303332656432343661353439313130
          38643866393536313337313939346166313535616162626131366236623239633334633466376363
          6138356239313663630a383362643838306664376630616462346562323262343764333030383763
          31333365363066653833343939363164323463366231623131646531613336666233616638306163
          3734346436393837386532323534616531363734636535643638
        lidatube_preferred_codec: 'mp3'
        # lidatube_memory: '4GiB'
        lidatube_sleep_interval: '300'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: 'servarr'
        wazuh_agent_groups: 'high_risk'
