- name: Configure base dependencies for all virtual machines
  hosts: all, !hypervisors
  tasks:
    - name: General virtual machine configuration
      ansible.builtin.import_role:
        name: base
      vars:
        base_shell_promt:
          - { path: '/home/{{ container_user }}/.bashrc', owner: '{{ container_user }}' }
          - { path: '/root/.bashrc', owner: 'root' }
