- name: Configure Virtual Private Server
  hosts: vps
  tasks:

    - name: Deploy internet facing Caddy
      ansible.builtin.import_role:
        name: caddy
      vars:
        caddy_user: '{{ container_user }}'
        caddy_data_vol: caddy_data
        caddy_conf_vol: caddy_conf
        caddy_conf_dir: /var/caddy
        caddy_internet_facing: true
        caddy_extensions:
          - github.com/corazawaf/coraza-caddy/v2
          - github.com/mholt/caddy-l4
        caddy_image: 'caddy-public'
        caddy_networks: 'host'
