---
- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true

- name: Ensure web tools are installed
  become: true
  ansible.builtin.package:
    name:
      - wget
      - curl
    state: present

- name: Ensure text editors are present
  become: true
  ansible.builtin.package:
    name:
      - vim
      - nano
    state: present

- name: Ensure RHEL specific packages are installed
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.package:
    name:
      - python3-libselinux
      - epel-release
      - audit
      - bind-utils
    state: present

- name: Ensure Debian specific packages are installed
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.package:
    name:
      - auditd
      - dnsutils
      - unattended-upgrades
      - apt-listchanges

    state: present

- name: Ensure misc tools are installed
  become: true
  ansible.builtin.package:
    name:
      # - qemu-guest-agent
      - rsync
      - telnet
      - acl
      - htop
      - traceroute
      # - incus-client
      - tree
    state: present
