---
- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true

- name: Install web tools
  become: true
  ansible.builtin.package:
    name:
      - wget
      - curl
    state: present

- name: Install text editors
  become: true
  ansible.builtin.package:
    name:
      - vim
      - nano
    state: present

- name: Install RHEL Family specific packages
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.package:
    name:
      - python3-libselinux
      - epel-release
      - audit
      - bind-utils
    state: present

- name: Install Debian Family specific packages
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.package:
    name:
      - auditd
      - dnsutils
    state: present

- name: Install misc tools
  become: true
  ansible.builtin.package:
    name:
      - tuned
      # - qemu-guest-agent
      - telnet
      - acl
      - htop
      - incus-client
    state: present
