---
- name: Ensure podman networks exist
  loop: "{{ quadlet_service_definition.networks | default([]) }}"
  loop_control:
    loop_var: network
  when: quadlet_service_definition.networks is defined and quadlet_service_definition.networks | length > 0
  become: true
  become_user: '{{ quadlet_service_definition.user }}'
  containers.podman.podman_network:
    name: '{{ network.name }}'
    subnet: '{{ network.subnet | default(omit) }}'
    gateway: '{{ network.gateway | default(omit) }}'
    force: true
