---
# - name: Build ports list
#   ansible.builtin.set_fact:
#     quadlet_service_ports: []

# - name: Add ports to quadlet_service_ports
#   ansible.builtin.set_fact:
#     quadlet_service_ports: >-
#       {{ quadlet_service_ports + [
#         (item.host_port + ':' + item.container_port)
#       ] }}
#   loop: "{{ quadlet_service_definition.ports }}"
#   when: quadlet_service_definition.ports is defined and quadlet_service_definition.ports | length > 0

- name: Ensure there's a podman network named {{ network.name }}
  loop: "{{ quadlet_service_definition.networks | default([]) }}"
  loop_control:
    loop_var: network
  when: quadlet_service_definition.networks is defined and quadlet_service_definition.networks | length > 0
  become: true
  become_user: '{{ quadlet_service_definition.user }}'
  containers.podman.podman_network:
    name: '{{ network.name }}'
    subnet: '{{ network.subnet | default(omit) }}'
    gateway: '{{ network.gateway | default(omit) }}'
    force: true
