---
- name: Build combined volumes list
  ansible.builtin.set_fact:
    combined_volumes: []

- name: Add named volumes to combined_volumes
  ansible.builtin.set_fact:
    combined_volumes: >-
      {{ combined_volumes + [
        (item.name + ':' + item.dest)
      ] }}
  loop: "{{ quadlet_service_definition.volumes }}"
  when: quadlet_service_definition.volumes is defined and quadlet_service_definition.volumes | length > 0


- name: Ensure Podman named volumes exist for {{ quadlet_service_definition.name }}
  loop: "{{ quadlet_service_definition.volumes | default([]) }}"
  loop_control:
    loop_var: volume
  when: volume.name is defined
  become: true
  become_user: '{{ quadlet_service_definition.user }}'
  containers.podman.podman_volume:
    state: present
    name: '{{ volume.name }}'
    driver: "{{ volume.driver | default(default_volume_driver) }}"
