---
- name: Pull latest code-server image
  become: true
  become_user: '{{ code_server_user }}'
  containers.podman.podman_image:
    name: '{{ registry_host }}.{{ internet_host }}/lscr-proxy/linuxserver/code-server'
    tag: 'latest'
    force: true
    username: '{{ code_server_registry_user | default(omit) }}'
    password: '{{ code_server_registry_pass | default(omit) }}'

- name: Build code-server custom image
  become: true
  become_user: '{{ code_server_user }}'
  notify: Restart code-server
  containers.podman.podman_image:
    name: '{{ code_server_image }}'
    tag: latest
    state: build
    force: true
    build:
      container_file: "{{ lookup('template', 'Containerfile.j2') }}"
      cache: false
