---
- name: Create Immich Server Quadlet file
  become: true
  become_user: '{{ immich_user }}'
  notify: Restart Immich
  containers.podman.podman_container:
    name: '{{ immich_server_container }}'
    image: ghcr.io/immich-app/immich-server:release
    state: quadlet
    quadlet_filename: '{{ immich_server_container }}'
    ports:
      - '{{ immich_http_port | 2283 }}:2283'
    network: '{{ immich_network }}'
    volumes:
      - '{{ immich_library_dir }}:/usr/src/app/upload'
      - /etc/localtime:/etc/localtime:ro
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      DB_DATABASE_NAME: '{{ immich_db_name }}'
      DB_USERNAME: '{{ immich_db_user }}'
      DB_PASSWORD: '{{ immich_db_pass }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target

- name: Create Immich Machine Learning Quadlet file
  become: true
  become_user: '{{ immich_user }}'
  notify: Restart Immich Machine Learning
  containers.podman.podman_container:
    name: '{{ immich_machine_learning_container }}'
    image: ghcr.io/immich-app/immich-machine-learning:release
    state: quadlet
    quadlet_filename: '{{ immich_machine_learning_container }}'
    network: '{{ immich_network }}'
    volumes:
      - '{{ immich_machine_learning_dir }}:/usr/src/app/upload'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target

- name: Create Redis Quadlet file
  become: true
  become_user: '{{ immich_user }}'
  notify: Restart Immich Redis
  containers.podman.podman_container:
    name: '{{ immich_redis_container }}'
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    state: quadlet
    quadlet_filename: '{{ immich_redis_container }}'
    network: '{{ immich_network }}'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
