---
- name: Ensure Immich is running
  become: true
  become_user: '{{ immich_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ immich_service_container }}'
    scope: user
