---
- name: Copy Prometheus configuration file
  notify: Restart Prometheus
  become: true
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: '{{ prometheus_config_dir }}/prometheus.yml'
    mode: '0644'
    owner: '{{ prometheus_user }}'
    group: '{{ prometheus_user }}'
