---
- name: Ensure Prometheus is running
  become: true
  become_user: '{{ prometheus_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ prometheus_container }}'
    scope: user
