---
- name: Restart Slskd
  become: true
  become_user: "{{ slskd_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ slskd_container }}"
    scope: user
