---
- name: Ensure there's a volume to store FitTrackee uploads
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ fittrackee_upload_vol }}'
    podman_user: '{{ fittrackee_user }}'

- name: Ensure there's a volume to store FitTrackee logs
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ fittrackcee_logs_vol }}'
    podman_user: '{{ fittrackee_user }}'
