---
- name: Ensure there's a directory on path {{ podman_bind_mount }}
  become: true
  ansible.builtin.file:
    path: "{{ podman_bind_mount }}"
    state: directory
    mode: "0777"
    recurse: true
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
