---
- name: Restart Grafana
  become: true
  become_user: "{{ grafana_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ grafana_container }}"
    scope: user
