- name: Create Caddy Quadlet file
  become: true
  become_user: '{{ caddy_user }}'
  notify: Restart Caddy
  containers.podman.podman_container:
    name: '{{ caddy_container }}'
    image: 'localhost/{{ caddy_image }}:latest'
    state: quadlet
    quadlet_filename: '{{ caddy_container }}'
    network: '{{ caddy_networks | default(omit) }}'
    ip: '{{ caddy_ip | default(omit) }}'
    # ports:
    #   - '443:443'
    #   - '443:443/udp'
    #   - '80:80'
    volumes:
      - '{{ caddy_conf_vol }}:/config:z'
      - '{{ caddy_data_vol }}:/data:z'
      - '{{ caddy_conf_dir }}:/etc/caddy/Caddyfile:z'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      CF_API_TOKEN: '{{ caddy_cloudflare_token | default(omit) }}'
      TS_AUTHKEY: '{{ caddy_ts_authkey | default(omit) }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
