---
- name: Create Wazuh Manager Quadlet file
  become: true
  become_user: '{{ wazuh_manager_user }}'
  notify: Restart Wazuh_manager
  containers.podman.podman_container:
    name: '{{ wazuh_manager_container }}'
    image: '{{ wazuh_manager_image }}:{{ wazuh_manager_version }}'
    network: '{{ wazuh_manager_network }}'
    hostname: '{{ wazuh_manager_hostname }}'
    state: quadlet
    quadlet_filename: '{{ wazuh_manager_container }}'
    ports:
      - '{{ wazuh_manager_agent | default("1514") }}:1514'
      - '{{ wazuh_manager_enrollment | default("1515") }}:1515'
      - '{{ wazuh_manager_syslog | default("514") }}:514/udp'
      - '{{ wazuh_manager_api | default("55000") }}:55000'
    volumes:
      - '{{ wazuh_manager_api_configuration_vol }}:/var/ossec/api/configuration:z'
      - '{{ wazuh_manager_etc_vol }}:/var/ossec/etc:z'
      - '{{ wazuh_manager_logs_vol }}:/var/ossec/logs:z'
      - '{{ wazuh_manager_queue_vol }}:/var/ossec/queue:z'
      - '{{ wazuh_manager_var_multigroups_vol }}:/var/ossec/var/multigroups:z'
      - '{{ wazuh_manager_integrations_vol }}:/var/ossec/integrations:z'
      - '{{ wazuh_manager_active_response_vol }}:/var/ossec/active-response/bin:z'
      - '{{ wazuh_manager_agentless_vol }}:/var/ossec/agentless:z'
      - '{{ wazuh_manager_wodles_vol }}:/var/ossec/wodles:z'
      - '{{ wazuh_manager_filebeat_etc_vol }}:/etc/filebeat:z'
      - '{{ wazuh_manager_filebeat_var_vol }}:/var/lib/filebeat:z'
      - '{{ wazuh_manager_ssl_certs_dir }}/root-ca-manager.pem:/etc/ssl/root-ca.pem:z'
      - '{{ wazuh_manager_ssl_certs_dir }}/wazuh.manager.pem:/etc/ssl/filebeat.pem:z'
      - '{{ wazuh_manager_ssl_certs_dir }}/wazuh.manager-key.pem:/etc/ssl/filebeat.key:z'
      - '{{ wazuh_manager_config_dir }}/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf:z'
      - '{{ wazuh_manager_config_dir }}/authd.pass:/var/ossec/etc/authd.pass:z'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      INDEXER_URL: 'https://{{ wazuh_manager_indexer_host }}:{{ wazuh_manager_indexer_port }}'
      INDEXER_USERNAME: '{{ wazuh_manager_indexer_username }}'
      INDEXER_PASSWORD: '{{ wazuh_manager_indexer_password }}'
      FILEBEAT_SSL_VERIFICATION_MODE: full
      SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
      SSL_CERTIFICATE: /etc/ssl/filebeat.pem
      SSL_KEY: /etc/ssl/filebeat.key
      API_USERNAME: '{{ wazuh_manager_api_username }}'
      API_PASSWORD: '{{ wazuh_manager_api_password }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
