---
- name: Create Loki Quadlet File
  become: true
  become_user: '{{ loki_user }}'
  notify: Restart Loki
  containers.podman.podman_container:
    name: '{{ loki_container }}'
    image: docker.io/grafana/loki:latest
    state: quadlet
    quadlet_filename: '{{ loki_container }}'
    ports:
      - '{{ loki_http_port | default(3100) }}:3100'
    volumes:
      - '{{ loki_logs_dir }}:/loki'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
