---
- name: Ensure Loki is running
  become: true
  become_user: '{{ loki_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ loki_container }}'
    scope: user
