---
- name: Create Flaresolverr container
  become: true
  become_user: '{{ flaresolverr_user }}'
  notify: Restart flaresolverr
  containers.podman.podman_container:
    name: '{{ flaresolverr_container }}'
    image: '{{ flaresolverr_image }}'
    state: quadlet
    quadlet_filename: '{{ flaresolverr_container }}'
    ports:
      - '{{ flaresolverr_http_port | default(8191) }}:8191'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
