when:
  - event: push
    branch: main
    path:
      - "images/ansible/Containerfile"
      - "requirements.yml"
  - event: manual

steps:
  build-woodpecker-ansible-image:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: registry.baremetalcloud.org:5000
      repo: ansible-woodpecker
      tags: latest
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
      dockerfile: images/ansible/Containerfile
      cache: true
      cache_repo: registry.baremetalcloud.org:5000/ansible-woodpecker-cache
      context: .