when:
  - event: push
    branch: main
    path:
      - "images/ansible/Containerfile"
      - "requirements.yml"
  - event: manual

steps:
  build-and-push:
    image: woodpeckerci/plugin-kaniko
    environment:
      PLUGIN_USERNAME:
        from_secret: REGISTRY_USER
      PLUGIN_PASSWORD:
        from_secret: REGISTRY_PASS
    settings:
      registry: registry.baremetalcloud.org:5000
      repo: registry.baremetalcloud.org:5000/ansible-woodpecker
      tags: latest
      dockerfile: images/ansible/Containerfile
      context: .