when:
  - event: push
    branch: main
    path:
      - "ansible/playbooks/monitoring.yml"
  - event: manual
    evaluate: "TARGET == 'monitoring'"

steps:
  run-playbook:
    image: registry.baremetalcloud.org:5000/ansible-woodpecker:latest
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
      VAULT_PASS:
        from_secret: ANSIBLE_VAULT_PASS
      BECOME_PASS:
        from_secret: ANSIBLE_BECOME_PASS
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - export ANSIBLE_HOST_KEY_CHECKING=False
      - printf "%s" "$VAULT_PASS" > /tmp/.vault_pass.txt
      - chmod o-w .
      - >
        ansible-playbook ansible/playbooks/monitoring.yml
        --vault-password-file /tmp/.vault_pass.txt
        -e "ansible_become_pass={{ lookup('env', 'BECOME_PASS') }}"