when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker.io/library/debian
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
  - name: a-test-step
    image: docker.io/library/golang:1.16
    commands:
      - echo "Testing ..."
      - chmod +x executable
      - ./executable