- name: Ensure Home Assistant is running
  become: true
  become_user: '{{ home_assistant_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ home_assistant_container }}'
    scope: user
