hypervisors:
  hosts:
    cube-hypervisor:
      ansible_host: 192.168.8.10
    hetzner-hypervisor:
      ansible_host: 46.224.174.85
      container_user: 'bmc'

bastions:
  hosts:
    cube-bastion:
      ansible_host: 10.0.1.10
      container_user: 'bmc'

remote_access_servers:
  hosts:
    hetzner-remote:
      ansible_host: 10.0.251.10
      container_user: 'bmc'

vpn_gateways:
  hosts:
    hetzner-vpn-gateway:
      ansible_host: 10.0.252.20
      container_user: 'bmc'
    cube-vpn-gateway:
      ansible_host: 10.0.6.20
      container_user: 'bmc'

vpn_servers:
  hosts:
    hetzner-vpn:
      ansible_host: 10.0.254.12
      # ansible_ssh_common_args: '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q {{ vps_proxy_jump_target }}"'
      container_user: 'bmc'

registry_servers:
  hosts:
    cube-registry:
      ansible_host: 10.0.0.14
      container_user: 'bmc'

code:
  hosts:
    cube-code:
      ansible_host: 10.0.0.15
      container_user: 'bmc'

dns_servers:
  hosts:
    cube-home-dms:
      ansible_host: 10.0.2.2
      container_user: bmc
    cube-vpn-dns:
      ansible_host: 10.0.2.4
      container_user: bmc
    cube-homelab-dns:
      ansible_host: 10.0.2.5
      container_user: bmc

automation_servers:
  hosts:
    cube-automation:
      ansible_host: 10.0.1.11
      container_user: 'bmc'

streaming:
  hosts:
    cube-streaming:
      ansible_host: 10.0.0.13
      container_user: bmc

security:
  hosts:
    hetzner-security:
      ansible_host: 10.0.254.10
      container_user: bmc

reverse_proxy_servers:
  hosts:
    cube-reverse-proxy:
      ansible_host: 10.0.5.10
      container_user: bmc
      caddy_profile: 'home-server'
    hetzner-reverse-proxy:
      ansible_host: 10.0.253.10
      container_user: 'bmc'
      caddy_profile: 'vps'

knowledge_management:
  hosts:
    hetzner-knowledge:
      ansible_host: 10.0.254.11
      container_user: bmc

monitoring_servers:
  hosts:
    cube-monitor:
      ansible_host: 10.0.7.10
      container_user: bmc
    hetzner-monitor:
      ansible_host: 10.0.251.11
      container_user: bmc

---

cube_server:
  hosts:
    cube-hypervisor:
    cube-bastion:
    cube-vpn-gateway:
    cube-registry:
    cube-code:
    cube-home-dms:
    cube-vpn-dns:
    cube-homelab-dns:
    cube-automation:
    cube-streaming:
    cube-reverse-proxy:
    cube-monitor:

hetzner_vps:
  hosts:
    hetzner-hypervisor:
    hetzner-remote:
    hetzner-vpn-gateway:
    hetzner-vpn:
    hetzner-security:
    hetzner-reverse-proxy:
    hetzner-knowledge:
    hetzner-monitor: