---
- name: Create Qbittorrent Quadlet file
  become: true
  become_user: '{{ qbittorrent_user }}'
  notify: Restart Qbittorrent
  containers.podman.podman_container:
    name: '{{ qbittorrent_container }}'
    image: '{{ qbittorrent_image }}'
    userns: 'keep-id'
    state: quadlet
    quadlet_filename: '{{ qbittorrent_container }}'
    ports:
      - '{{ qbittorrent_http_port }}:8080'
      - '{{ qbittorrent_torrenting_port }}:6881'
      - '{{ qbittorrent_torrenting_port }}:6881/udp'
    dns: '{{ qbittorrent_dns_servers }}'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      TORRENTING_PORT: '{{ qbittorrent_torrenting_port }}'
    volumes:
      - '{{ qbittorrent_data }}:/config:z'
      - '{{ qbittorrent_downloads }}:/downloads'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
