---
- name: Ensure nebula-sync is running
  become: true
  become_user: '{{ pihole_nebula_sync_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ pihole_nebula_sync_container }}'
    scope: user
