---
- name: Restart pihole_nebula_sync
  become: true
  become_user: '{{ pihole_nebula_sync_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ pihole_nebula_sync_container }}'
    scope: user
