---
- name: Ensure there's a soft limit for maximum open files
  become: true
  community.general.pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 1048576

- name: Ensure there's a hard limit for maximum open files
  become: true
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 1048576

- name: Ensure there's a soft limit for maximum open files (root)
  become: true
  community.general.pam_limits:
    domain: 'root'
    limit_type: soft
    limit_item: nofile
    value: 1048576

- name: Ensure there's a hard limit for maximum open files (root)
  become: true
  community.general.pam_limits:
    domain: 'root'
    limit_type: hard
    limit_item: nofile
    value: 1048576

- name: Ensure there's a soft limit for locked-in-memory address space
  become: true
  community.general.pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: memlock
    value: unlimited

- name: Ensure there's a hard limit for locked-in-memory address space
  become: true
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: memlock
    value: unlimited

- name: Ensure there's a soft limit for locked-in-memory address space (root)
  become: true
  community.general.pam_limits:
    domain: 'root'
    limit_type: soft
    limit_item: memlock
    value: unlimited

- name: Ensure there's a hard limit for locked-in-memory address space (root)
  become: true
  community.general.pam_limits:
    domain: 'root'
    limit_type: hard
    limit_item: memlock
    value: unlimited
