- name: Ensure incus can mount lvm storage
  become: true
  ansible.builtin.package:
    name:
      - lvm2
    state: present

- name: Ensure Incus is installed and updated
  become: true
  ansible.builtin.apt:
    name: incus
    state: present
    update_cache: true
